export const person: Person = {
    name: "Vasia",
        height: '185',
    mass: '21',
    hair_color: 'green',
    skin_color: 'white',
    eye_color: 'green',
    birth_year: '2002',
    gender: 'male',
    homeworld: 'Earth',
    films: ['Star wars', 'Equilizer'],
    species: [],
    vehicles: ['BMW'],
    created: new Date('15.04.2008'),
}